name: CI Workflow

on:
  push:
  workflow_dispatch:  # для ручного запуску

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонування репозиторію
        uses: actions/checkout@v3

      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск тестів
        run: |
          pytest --maxfail=1 --disable-warnings -q
